name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Laravel App
    uses: ./.github/workflows/build.yaml
    with:
      php-version: "8.3"
      cache-key: ${{ github.sha }}-php-vendor-cache
